name: Build and Deploy Java JAR (Gradle)

on:
  # FIX: The trigger requires a map structure, not a bare key.
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17' # Ensure java-version is a string
          cache: gradle
